development:
  adapter: mysql2
  encoding: utf8
  database: movie_theatre_development
  pool: 5
  username: root

test:
  adapter: mysql2
  encoding: utf8
  database: movie_theatre_test
  pool: 5
  username: root